#!/bin/bash
#SBATCH --job-name=birdclef-ensemble
#SBATCH --partition=l40s
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=64G
#SBATCH --time=12:00:00
#SBATCH --output=logs/ensemble_%j.log
#SBATCH --error=logs/ensemble_%j.log

# ── Multi-backbone ensemble + cross-pollinated self-training ──
#
# Sequentially trains 4 models with different backbones on different folds,
# then runs N iterations where each model is retrained against pseudo-labels
# generated by the ensemble of THE OTHER models (leave-one-out, prevents
# self-reinforcement of single-model bias).
#
# Usage:
#   # Full pipeline from scratch (4 baselines + 3 self-training iterations):
#   sbatch scripts/ensemble_pipeline.sh
#
#   # Resume with existing baseline checkpoints (skip phase 1):
#   BASELINE_CKPTS="path/m0.ckpt,path/m1.ckpt,path/m2.ckpt,path/m3.ckpt" \
#     sbatch scripts/ensemble_pipeline.sh
#
#   # Customize:
#   BACKBONES="efficientnet_b0,mobilenetv3_small,resnet18,convnext_tiny" \
#   FOLDS="0,1,2,3" N_ITERATIONS=3 sbatch scripts/ensemble_pipeline.sh

PROJECT_DIR="$HOME/BirdCallClassifier"
ENV_NAME="birdcallclassifier"
CKPT_DIR="$PROJECT_DIR/checkpoints"

mkdir -p "$PROJECT_DIR/logs"

# ── Load modules ──
module purge
module load cuda/12.8.0-dh6b
module load miniconda3/latest
eval "$(conda shell.bash hook)"
conda activate "$ENV_NAME"

cd "$PROJECT_DIR"

# ── Config (override via env vars) ──
JOB_ID="${SLURM_JOB_ID:-local_$(date +%Y%m%d_%H%M%S)}"
SEED="${SEED:-42}"
THRESHOLD="${THRESHOLD:-0.8}"
MAX_PER_SPECIES="${MAX_PER_SPECIES:-500}"
PSEUDO_DISTILL_WEIGHT="${PSEUDO_DISTILL_WEIGHT:-1.0}"
PSEUDO_POWER_T="${PSEUDO_POWER_T:-2.0}"
# MixUp posture (Ari preference): off for baselines, gentle for cross-pollinated retrain only.
# Past attempts at α=0.4 consistently hurt Kaggle scores.
PSEUDO_MIXUP_ALPHA="${PSEUDO_MIXUP_ALPHA:-0.2}"
MIXUP_ALPHA="${MIXUP_ALPHA:-0.0}"          # off for baselines
MULTI_MIX_PROB="${MULTI_MIX_PROB:-0.0}"    # off for baselines (overlaps with bg_mix)
# Soundscape background injection — main new aug lever for round 2.
# Mixes unlabeled Pantanal soundscapes as noise behind clean focal recordings.
BG_MIX_PROB="${BG_MIX_PROB:-0.5}"
BG_SNR_MIN="${BG_SNR_MIN:-3}"
BG_SNR_MAX="${BG_SNR_MAX:-15}"
RETRAIN_EPOCHS="${RETRAIN_EPOCHS:-15}"
RETRAIN_LR="${RETRAIN_LR:-2e-5}"
N_ITERATIONS="${N_ITERATIONS:-3}"
BASELINE_EPOCHS="${BASELINE_EPOCHS:-30}"
BATCH_SIZE="${BATCH_SIZE:-64}"
NUM_WORKERS="${NUM_WORKERS:-8}"
MIN_DURATION="${MIN_DURATION:-5.0}"
MAX_DURATION="${MAX_DURATION:-5.0}"

# Round 2: all 4 backbones under 40M, real architectural diversity (BirdSet
# pretrained EfficientNet + ImageNet pretrained EfficientNet/MobileNet/RegNet).
BACKBONES_CSV="${BACKBONES:-birdset_b1,efficientnet_b0,mobilenetv3_large,regnety_002}"
FOLDS_CSV="${FOLDS:-0,1,2,3}"

# Per-backbone learning rate (BirdSet wants lower since it's already domain-pretrained;
# ConvNeXt-style LayerNorm models want very low to avoid LayerNorm divergence).
get_lr_for_backbone() {
    case "$1" in
        birdset_b1|birdset_b0)              echo "${BIRDSET_LR:-5e-5}" ;;
        convnext_tiny|convnext_*)           echo "${CONVNEXT_LR:-5e-5}" ;;
        *)                                   echo "${BASELINE_LR:-1.5e-4}" ;;
    esac
}

DISTILL_MANIFEST="${DISTILL_MANIFEST:-$PROJECT_DIR/data/distill_manifest.csv}"
HARD_NEGATIVES="${HARD_NEGATIVES:-1}"
VALID_REGIONS="$PROJECT_DIR/data/valid_regions.json"

HARD_NEG_ARG="--hard_negatives"
[ "$HARD_NEGATIVES" = "0" ] && HARD_NEG_ARG="--no_hard_negatives"
DISTILL_MANIFEST_ARG=""
if [ -n "$DISTILL_MANIFEST" ] && [ -f "$DISTILL_MANIFEST" ]; then
    DISTILL_MANIFEST_ARG="--distill_manifest $DISTILL_MANIFEST"
fi

IFS=',' read -ra BACKBONES_ARR <<< "$BACKBONES_CSV"
IFS=',' read -ra FOLDS_ARR <<< "$FOLDS_CSV"
N_MODELS=${#BACKBONES_ARR[@]}
if [ "$N_MODELS" -ne "${#FOLDS_ARR[@]}" ]; then
    echo "ERROR: BACKBONES has $N_MODELS entries but FOLDS has ${#FOLDS_ARR[@]}"
    exit 1
fi

echo "=== Ensemble pipeline ==="
echo "Job: $JOB_ID"
echo "Backbones: ${BACKBONES_ARR[*]}"
echo "Folds:     ${FOLDS_ARR[*]}"
echo "Iterations: $N_ITERATIONS"
echo "---"

# ── Preprocess: detect active vocal regions (cached) ──
if [ ! -f "$VALID_REGIONS" ]; then
    echo "Step 0: Detecting active vocal regions..."
    python scripts/preprocess_activity.py \
        --data-dir "$PROJECT_DIR/data" \
        --output "$VALID_REGIONS"
fi

# ── Helper: best-AUC ckpt picker ──
pick_best_ckpt() {
    local run_dir="$1"
    ls "$run_dir"/birdclef-birdset-*.ckpt 2>/dev/null \
        | awk -F'val_macro_auc=' '{print $2"\t"$0}' \
        | sort -k1,1 -gr | head -1 | cut -f2-
}

# ── Phase 1: Train 4 baseline models ──
declare -a CURRENT_CKPTS
if [ -n "$BASELINE_CKPTS" ]; then
    echo ""
    echo "=== Phase 1: Using provided baseline checkpoints ==="
    IFS=',' read -ra CURRENT_CKPTS <<< "$BASELINE_CKPTS"
    if [ "${#CURRENT_CKPTS[@]}" -ne "$N_MODELS" ]; then
        echo "ERROR: BASELINE_CKPTS has ${#CURRENT_CKPTS[@]} entries but expected $N_MODELS"
        exit 1
    fi
    for i in "${!CURRENT_CKPTS[@]}"; do
        echo "  Model $i (${BACKBONES_ARR[$i]}): ${CURRENT_CKPTS[$i]}"
    done
else
    echo ""
    echo "=== Phase 1: Training $N_MODELS baseline models ==="
    for i in $(seq 0 $((N_MODELS - 1))); do
        BACKBONE="${BACKBONES_ARR[$i]}"
        FOLD="${FOLDS_ARR[$i]}"
        RUN_ID="${JOB_ID}_m${i}_${BACKBONE}_fold${FOLD}_baseline"
        LR=$(get_lr_for_backbone "$BACKBONE")
        echo ""
        echo "── Baseline model $i/$((N_MODELS-1)): backbone=$BACKBONE, fold=$FOLD, lr=$LR ──"

        python src/train.py \
            --data_dir "$PROJECT_DIR/data" \
            --backbone "$BACKBONE" \
            --batch_size "$BATCH_SIZE" \
            --num_workers "$NUM_WORKERS" \
            --max_epochs "$BASELINE_EPOCHS" \
            --lr "$LR" \
            --precision bf16 \
            --save_dir "$CKPT_DIR" \
            --seed "$((SEED + i))" \
            --loss focal \
            --label_smoothing 0.05 \
            --mixup_alpha "$MIXUP_ALPHA" \
            --mix_prob "$MULTI_MIX_PROB" \
            --bg_mix_prob "$BG_MIX_PROB" \
            --bg_snr_min "$BG_SNR_MIN" \
            --bg_snr_max "$BG_SNR_MAX" \
            --n_folds 5 \
            --fold "$FOLD" \
            --min_duration "$MIN_DURATION" \
            --max_duration "$MAX_DURATION" \
            --full_files \
            --no_distill \
            --balance_alpha 0.5 \
            --save_top_k 1 \
            --use_wandb \
            --wandb_project birdclef-2026 \
            --run_name "$RUN_ID" \
            --run_id "$RUN_ID" \
            --valid_regions "$VALID_REGIONS" \
            $DISTILL_MANIFEST_ARG \
            $HARD_NEG_ARG

        BEST=$(pick_best_ckpt "$CKPT_DIR/$RUN_ID")
        if [ -z "$BEST" ]; then
            echo "ERROR: No checkpoint for model $i in $CKPT_DIR/$RUN_ID"
            exit 1
        fi
        CURRENT_CKPTS[$i]="$BEST"
        echo "Model $i baseline best: $BEST"
    done
fi

# ── Phase 2: N iterations of cross-pollinated self-training ──
for ITER in $(seq 1 "$N_ITERATIONS"); do
    echo ""
    echo "════════════════════════════════════════════════"
    echo "  Iteration $ITER / $N_ITERATIONS"
    echo "  Current ensemble:"
    for i in "${!CURRENT_CKPTS[@]}"; do
        echo "    [$i] ${BACKBONES_ARR[$i]}: ${CURRENT_CKPTS[$i]}"
    done
    echo "════════════════════════════════════════════════"

    # ── For each model i: pseudo-label with ensemble of OTHER models ──
    declare -a NEXT_CKPTS
    for i in $(seq 0 $((N_MODELS - 1))); do
        BACKBONE="${BACKBONES_ARR[$i]}"
        FOLD="${FOLDS_ARR[$i]}"
        TEACHER_CKPTS=""
        TEACHER_BACKBONES=""
        for j in $(seq 0 $((N_MODELS - 1))); do
            if [ "$i" != "$j" ]; then
                if [ -z "$TEACHER_CKPTS" ]; then
                    TEACHER_CKPTS="${CURRENT_CKPTS[$j]}"
                    TEACHER_BACKBONES="${BACKBONES_ARR[$j]}"
                else
                    TEACHER_CKPTS="${TEACHER_CKPTS},${CURRENT_CKPTS[$j]}"
                    TEACHER_BACKBONES="${TEACHER_BACKBONES},${BACKBONES_ARR[$j]}"
                fi
            fi
        done

        ITER_PSEUDO_CSV="$PROJECT_DIR/data/pseudo_labels_iter${ITER}_excl${i}.csv"
        RUN_ID="${JOB_ID}_m${i}_${BACKBONE}_fold${FOLD}_iter${ITER}"

        echo ""
        echo "── Iter $ITER, Model $i: ensemble teacher = OTHER ${BACKBONES_ARR[*]} (excl. $BACKBONE) ──"
        echo "Teachers: $TEACHER_CKPTS"

        # ── Step A: cross-pollinated pseudo-labels ──
        python scripts/pseudo_label.py \
            --checkpoints "$TEACHER_CKPTS" \
            --backbones "$TEACHER_BACKBONES" \
            --data-dir "$PROJECT_DIR/data" \
            --output "$ITER_PSEUDO_CSV" \
            --threshold "$THRESHOLD" \
            --max-per-species "$MAX_PER_SPECIES" \
            --match-train-distribution \
            --batch-size 64 \
            --use_wandb \
            --wandb_project birdclef-2026 \
            --run_name "pseudo-${RUN_ID}"

        N_PSEUDO=$(tail -n +2 "$ITER_PSEUDO_CSV" 2>/dev/null | wc -l)
        echo "Iter $ITER, Model $i: pseudo-labeled segments = $N_PSEUDO"
        if [ "$N_PSEUDO" -eq 0 ]; then
            echo "WARNING: No pseudo-labels for model $i this iteration. Carrying prior ckpt forward."
            NEXT_CKPTS[$i]="${CURRENT_CKPTS[$i]}"
            continue
        fi

        # ── Step B: warm-start retrain with leave-one-out pseudo-labels ──
        python src/train.py \
            --data_dir "$PROJECT_DIR/data" \
            --backbone "$BACKBONE" \
            --batch_size "$BATCH_SIZE" \
            --num_workers "$NUM_WORKERS" \
            --max_epochs "$RETRAIN_EPOCHS" \
            --lr "$RETRAIN_LR" \
            --precision bf16 \
            --save_dir "$CKPT_DIR" \
            --seed "$((SEED + i + ITER * 100))" \
            --loss focal \
            --label_smoothing 0.05 \
            --mixup_alpha "$MIXUP_ALPHA" \
            --mix_prob "$MULTI_MIX_PROB" \
            --bg_mix_prob "$BG_MIX_PROB" \
            --bg_snr_min "$BG_SNR_MIN" \
            --bg_snr_max "$BG_SNR_MAX" \
            --n_folds 5 \
            --fold "$FOLD" \
            --min_duration "$MIN_DURATION" \
            --max_duration "$MAX_DURATION" \
            --full_files \
            --no_distill \
            --balance_alpha 0.5 \
            --save_top_k 1 \
            --use_wandb \
            --wandb_project birdclef-2026 \
            --run_name "$RUN_ID" \
            --run_id "$RUN_ID" \
            --valid_regions "$VALID_REGIONS" \
            --pseudo_labels "$ITER_PSEUDO_CSV" \
            --pseudo_distill_weight "$PSEUDO_DISTILL_WEIGHT" \
            --pseudo_power_t "$PSEUDO_POWER_T" \
            --pseudo_mixup_alpha "$PSEUDO_MIXUP_ALPHA" \
            --warmstart "${CURRENT_CKPTS[$i]}" \
            $DISTILL_MANIFEST_ARG \
            $HARD_NEG_ARG

        BEST=$(pick_best_ckpt "$CKPT_DIR/$RUN_ID")
        if [ -z "$BEST" ]; then
            echo "ERROR: Iter $ITER, model $i: no checkpoint produced. Carrying prior ckpt forward."
            NEXT_CKPTS[$i]="${CURRENT_CKPTS[$i]}"
        else
            NEXT_CKPTS[$i]="$BEST"
            echo "Iter $ITER, Model $i best: $BEST"
        fi
    done

    # ── Promote new checkpoints for next iteration ──
    for i in "${!NEXT_CKPTS[@]}"; do
        CURRENT_CKPTS[$i]="${NEXT_CKPTS[$i]}"
    done
    unset NEXT_CKPTS
done

# ── Final manifest ──
MANIFEST="$CKPT_DIR/ensemble_manifest_${JOB_ID}.txt"
echo ""
echo "=== Pipeline complete ==="
{
    echo "# Ensemble manifest from job $JOB_ID"
    echo "# Format: backbone<TAB>fold<TAB>checkpoint"
    for i in "${!CURRENT_CKPTS[@]}"; do
        printf "%s\t%s\t%s\n" "${BACKBONES_ARR[$i]}" "${FOLDS_ARR[$i]}" "${CURRENT_CKPTS[$i]}"
    done
} > "$MANIFEST"

echo "Final ensemble:"
cat "$MANIFEST"
echo ""
echo "Manifest written to: $MANIFEST"
echo ""
echo "To submit ensemble (extracts run_id from each ckpt path):"
echo "  bash scripts/submit.sh \$(grep -v '^#' '$MANIFEST' | cut -f3 | xargs -n1 dirname | xargs -n1 basename)"
